### ISSUE TITLE
Feishin won't play songs on Artix Linux, MPV "Socket is closed"

### ISSUE THREAD

**Issue by swishkin** [jeffvli/feishin#179]
## Expected Behavior

Feishin should play songs

## Current Behavior

Feishin shows the pause button instead of play button, but does not play songs when a play button is clicked.

Console log:

```
23:41:15.677 › APPIMAGE env is not defined, current application is not an AppImage
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Initializing MPV with data:  {
  extraParameters: [],
  properties: {
    'audio-exclusive': 'no',
    'gapless-audio': 'weak',
    replaygain: 'no',
    'replaygain-clip': true,
    'replaygain-preamp': 0
  }
}
Setting mpv params:  [ '--idle=yes', '--prefetch-playlist=yes' ]
Setting MPV properties:  {
  'audio-exclusive': 'no',
  'gapless-audio': 'weak',
  replaygain: 'no',
  'replaygain-clip': true,
  'replaygain-preamp': 0
}
(node:15838) UnhandledPromiseRejectionWarning: #<Object>
(Use `feishin --trace-warnings ...` to show where the warning was created)
(node:15838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error in main process Error: Socket is closed
    at new NodeError (node:internal/errors:387:5)
    at Socket._writeGeneric (node:net:864:8)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:343343
    at new Promise (<anonymous>)
    at l.send (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:343069)
    at l.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:342089) {
  code: 'ERR_SOCKET_CLOSED'
}
MPV failed to set volume {
  errcode: 8,
  verbose: 'MPV is not running',
  method: 'volume()',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:343165\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at l.send (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:343069)\n' +
    '    at l.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:342089)\n' +
    '    at y.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:344520)\n' +
    '    at y.volume (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:346750)\n' +
    '    at IpcMainImpl.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:500724)\n' +
    '    at IpcMainImpl.emit (node:events:513:28)\n' +
    '    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81053)'
}
MPV Event: status mute false []
MPV Event: status pause false []
MPV Event: status duration undefined []
MPV Event: status volume 100 []
MPV Event: status filename undefined []
MPV Event: status path undefined []
MPV Event: status media-title undefined []
MPV Event: status playlist-pos -1 []
MPV Event: status playlist-count 0 []
MPV Event: status loop false []
MPV Event: stopped
MPV failed to remove song from playlist {
  errcode: 3,
  verbose: 'ipcCommand invalid',
  method: null,
  arguments: [ 0 ],
  errmessage: 'error running command',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at e.exports.reject (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:343787)\n' +
    '    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:341561\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at l.dataHandler (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:341300)\n' +
    '    at Socket.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:342761)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:315:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:289:9)\n' +
    '    at Socket.Readable.push (node:internal/streams/readable:228:10)'
}
MPV failed to seek to 0 {
  errcode: 10,
  verbose: 'IPC connection error',
  method: 'connect ECONNREFUSED /tmp/node-mpv.sock',
  arguments: 'seek()',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at Socket.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:347282)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}
MPV Event: status pause true []
MPV failed to load song {
  errcode: 10,
  verbose: 'IPC connection error',
  method: 'connect ECONNREFUSED /tmp/node-mpv.sock',
  arguments: 'load()',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at Socket.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:363319)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}
MPV Event: status volume 50 []
MPV failed to load next song {
  errcode: 10,
  verbose: 'IPC connection error',
  method: 'connect ECONNREFUSED /tmp/node-mpv.sock',
  arguments: 'load()',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at Socket.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:363319)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}
MPV Event: status pause false []
(node:15838) UnhandledPromiseRejectionWarning: #<Object>
(node:15838) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

## Steps to Reproduce

1. Install Feishin 

2. Run Feishin in command line (to show output)

3. Set up Feishin with MPV binary and Navidrome server address, user, password, etc.

4. Play any song

5. Song does not play

## Possible Solution (Not obligatory)

It looks like Feishin thinks the MPV socket is closed; I'm not sure how to troubleshoot that.

## Context

I'm able to use Feishin normally on Windows, but am trying to get it set up on Linux as well. When I did install, configure, and start it, it won't play any songs from my Navidrome server (hosted on my domain, behind a reverse proxy).

## Your Environment

-   Application version (e.g. v0.2.0) : 0.2.0
-   Operating System and version (e.g. Windows 10) : Artix Linux on Linux kernel 6.1.12
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome [0.49.3](https://github.com/navidrome/navidrome/releases/tag/v0.49.3) (8b93962f)
-   Node version (if developing locally) : N/A
-   Possibly important: Artix uses runit, _not_ systemd
-   permissions on node-mpv.sock: `srw------- 1 [user] wheel 0 Jul 10 23:51 /tmp/node-mpv.sock`

**Comment by jeffvli** [comment]
My recommendation is to try downloading different versions of mpv (or building it from source) and re-setting the mpv path in Feishin's settings. There have been other reports of older mpv versions not working properly albeit I'm not sure what the exact errors of those were.

Can you try that and report back?


Edit: Another possibility is that mpv or another Feishin instance was already open before you opened the app. Kill all other Feishin processes and try again.

**Comment by swishkin** [comment]
I tried installing MPV via yay, as I'd installed it via Pacman previously. This builds it from source, I think. It didn't make any change, unfortunately.

I also tried killing MPV and Feishin via pkill, and then started up Feishin. Feishin still fails to play any audio.

**Comment by jeffvli** [comment]
Are you still encountering this issue? Known working versions of mpv include v0.35.x and v0.36.x if you want to try again with those versions.

**Comment by swishkin** [comment]
I'm running mpv 0.36.0 (likely the build I installed from yay/AUR), and it still isn't playing anything. I haven't updated Feishin since then, so if there have been updates, I'll test on the newer versions today.

**Comment by swishkin** [comment]
Updated to 0.3.0 and it still doesn't play anything. :/

[Here's](https://n2b.io/upload/snail-viper-pug) the stderr + stdout from launching Feishin, connecting to my server (which remembered my password and happened automatically :partying_face:), then attempting to play a playlist a few times, an individual song once or twice, and then closing.

Does anything in there give you an idea what's going wrong on my system?

**Comment by jeffvli** [comment]
I don't use artix linux so it's difficult for me to attempt to reproduce it. From the logs it just seems like mpv is having trouble connecting via the module I use as the controller.

Some other things to consider:
- If you're connecting to your Navidrome server that's behind a reverse proxy, try re-adding the server using the private IP instead
- Try playing songs directly via the `mpv` using both local files as well as using a navidrome stream (you can get the stream URL go going to the Navidrome Web UI and viewing the network requests via devtools when playing songs).

**Comment by swishkin** [comment]
Just opened 0.5.1 and it's playing just fine. Not sure if package updates/installs/uninstalls fixed it, or something on your side, but I'm not having the problem anymore! 🎉
