### ISSUE TITLE
Opening feishin freezes my linux computer

### ISSUE THREAD

**Issue by JustDoom** [jeffvli/feishin#218]
## Expected Behavior

It open normally without freezing my whole computer

## Current Behavior

When I open Feishin it freezes everything. All my windows freeze and I cant interact with anything but my mouse still moves. After about 20 seconds it updates once and my actions register then it freezes again for about 30 seconds and it goes back to normal and feishin opens. Each time I have opened it I think it gets a litter quicker but might be unrelated.
Not sure what screenshots I can provide that help with this.
Nothing is in the console after I open it when it loads

This happens on both my popos laptop and PC

## Steps to Reproduce

Open Feishin via terminal or double clicking it

I tried with the terminal and got this output
```
dino@pop-os:~/Applications$ ./Feishin-0.3.0-linux-x86_64.AppImage 
[17439:0814/165825.709273:ERROR:connection.cc(579)] Cannot send request of length 21086496
16:58:25.862 › Checking for update
// STOPS HERE ON THE FIRST FREEZE
[17481:0814/165826.119966:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[17481:0814/165827.039665:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[17481:0814/165827.040961:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Initializing MPV with data:  {
  extraParameters: [],
  properties: {
    'audio-exclusive': 'no',
    'gapless-audio': 'weak',
    replaygain: 'no',
    'replaygain-clip': true,
    'replaygain-preamp': 0
  }
}
Setting mpv params:  [ '--idle=yes', '--prefetch-playlist=yes' ]
Setting MPV properties:  {
  'audio-exclusive': 'no',
  'gapless-audio': 'weak',
  replaygain: 'no',
  'replaygain-clip': true,
  'replaygain-preamp': 0
}
(node:17439) UnhandledPromiseRejectionWarning: #<Object>
(Use `feishin --trace-warnings ...` to show where the warning was created)
(node:17439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error in main process Error: Socket is closed
    at new NodeError (node:internal/errors:399:5)
    at Socket._writeGeneric (node:net:920:8)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at /tmp/.mount_FeishiWE5YcB/resources/app.asar/dist/main/main.js:14:343343
    at new Promise (<anonymous>)
    at l.send (/tmp/.mount_FeishiWE5YcB/resources/app.asar/dist/main/main.js:14:343069)
    at l.setProperty (/tmp/.mount_FeishiWE5YcB/resources/app.asar/dist/main/main.js:14:342089) {
  code: 'ERR_SOCKET_CLOSED'
}
MPV failed to load song {
  errcode: 8,
  verbose: 'MPV is not running',
  method: 'emit()',
  arguments: [
    'http://10.42.0.248:8096/audio&playSessionId=&container=opus,mp3,aac,m4a,m4b,flac,wav,ogg&transcodingContainer=ts&transcodingProtocol=hls',
    'replace'
  ],
  options: {
    replace: 'Replace the currently playing title',
    append: 'Append the title to the playlist',
    'append-play': 'Append the title and when it is the only title in the list start playback'
  },
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/tmp/.mount_FeishiWE5YcB/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at y.load (/tmp/.mount_FeishiWE5YcB/resources/app.asar/dist/main/main.js:14:362479)\n' +
    '    at IpcMainImpl.<anonymous> (/tmp/.mount_FeishiWE5YcB/resources/app.asar/dist/main/main.js:14:499550)\n' +
    '    at IpcMainImpl.emit (node:events:513:28)\n' +
    '    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88498)\n' +
    '    at WebContents.emit (node:events:513:28)'
}
(node:17439) UnhandledPromiseRejectionWarning: #<Object>
(node:17439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
MPV Event: status pause false []
MPV Event: status duration undefined []
MPV Event: status volume 62 []
MPV Event: status filename undefined []
MPV Event: status path undefined []
MPV Event: status media-title undefined []
MPV Event: status playlist-pos -1 []
MPV Event: status playlist-count 0 []
MPV Event: status loop false []
MPV Event: stopped
MPV Event: status filename universal?userId=b3f6a919d0f40c92e20b0dd78cc6&deviceId=&audioCodec=aac&api_key=767e423b7b645b9b9b73e0548535&playSessionId=&container=opus,mp3,aac,m4a,m4b,flac,wav,ogg&transcodingContainer=ts&transcodingProtocol=hls []
MPV Event: status path http://10.42.0.248:8096/audio/eb3725ead7bbfaa09b9e3a0b858bb0/universal?userId=b3f69819d0f40cc972e2b0dd748cc6&deviceId=&audioCodec=aac&api_key=767e4233b7b64529b9b76e05948535&playSessionId=&container=opus,mp3,aac,m4a,m4b,flac,wav,ogg&transcodingContainer=ts&transcodingProtocol=hls []
MPV Event: status media-title universal?userId=b3f6a9819d0f40cc972e20dd748cc6&deviceId=&audioCodec=aac&api_key=767e4233b7b645b29b9b7365948535&playSessionId=&container=opus,mp3,aac,m4a,m4b,flac,wav,ogg&transcodingContainer=ts&transcodingProtocol=hls []
MPV Event: status playlist-pos 0 []
MPV Event: status playlist-count 1 []
MPV Event: status pause true []
(node:17439) UnhandledPromiseRejectionWarning: #<Object>
(node:17439) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
MPV Event: status duration 181.488 []
MPV Event: status media-title The Man With The Hand Instead Of A Gun []
16:58:28.537 › Update for version 0.3.0 is not available (latest version: 0.3.0, downgrade is disallowed).
16:58:28.537 › checkForUpdatesAndNotify called, downloadPromise is null
```

## Possible Solution (Not obligatory)

Thinking it looks like something with the update checker? not sure though

## Context

I just want to listen to music without freezing everything :(

## Your Environment

- Running 0.3.0
![image](https://github.com/jeffvli/feishin/assets/61824552/81c61012-4ed9-40f4-9526-73ef153a41f9)

**Comment by Gecked-Deck** [comment]
Try disabling auto-updates, it should skip this step.
![image](https://github.com/jeffvli/feishin/assets/104325921/e0d390fd-ae98-4fe1-a304-dd3b7f001536)

**Comment by JustDoom** [comment]
![image](https://github.com/jeffvli/feishin/assets/61824552/a1b0d273-b4d6-4a29-965f-9107a6f4a786)
didnt seem to help. guess thats not it then

**Comment by JustDoom** [comment]
didnt help, guess it isnt that (sorry, sent wrong image for a sec lol)
![image](https://github.com/jeffvli/feishin/assets/61824552/67642ff5-306d-4c69-9774-854611e4bb2a)

**Comment by marksdestiny** [comment]
I have this issue as well. My PC freezes during the startup of the application for quite a while. Also when I try to play a song, the application goes into and endless loop between playing and pausing the song in an 100ms interval. I think it might be a problem with mpv.

The terminal output can be seen in [console.log](https://github.com/jeffvli/feishin/files/12436500/console.log).

**Comment by jeffvli** [comment]
@marksdestiny The mpv start/stop issue is likely to do with your mpv version. Try downloading the latest version or build from source.

The freezing issue doesn't seem to be from the updater but rather it's an [internal Electron issue](https://github.com/electron/electron/issues/32760). I saw some comments that the latest Electron versions have resolved it so I'll bump up the version.

**Comment by JustDoom** [comment]
Seems fine now, launches on my PC and laptop without any issues
