### ISSUE TITLE
User MPV scripts may interfear with the program

### ISSUE THREAD

**Issue by 137-Trimethylxanthin** [jeffvli/feishin#242]
## Expected Behavior

it should play the music.

## Current Behavior

It is stuck at 0:00 and the terminal gives some errors if you have it open via termianl
from my limited understanding of mpv, i think it crashes at the start
(replaced username with %user%)
at start:
```powershell
Error in main process TypeError: Error processing argument at index 0, conversion failure from mediatracknext
    at IpcMainImpl.<anonymous> (C:\Users\%user%\AppData\Local\Programs\feishin\resources\app.asar\dist\main\main.js:14:522585)
    at IpcMainImpl.emit (node:events:513:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81053)
    at EventEmitter.emit (node:events:513:28)
Initializing MPV with data:  {
  extraParameters: [ '' ],
  properties: {
    'audio-exclusive': 'no',
    'gapless-audio': 'weak',
    replaygain: 'track',
    'replaygain-clip': true,
    'replaygain-preamp': 0
  }
}
Setting mpv params:  [ '--idle=yes', '--prefetch-playlist=yes', '' ]
Setting MPV properties:  {
  'audio-exclusive': 'no',
  'gapless-audio': 'weak',
  replaygain: 'track',
  'replaygain-clip': true,
  'replaygain-preamp': 0
}
(node:12904) UnhandledPromiseRejectionWarning: #<Object>
(Use `Feishin --trace-warnings ...` to show where the warning was created)
(node:12904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error in main process Error: Socket is closed
    at new NodeError (node:internal/errors:387:5)
    at Socket._writeGeneric (node:net:864:8)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at C:\Users\%user%\AppData\Local\Programs\feishin\resources\app.asar\dist\main\main.js:14:343343
    at new Promise (<anonymous>)
    at l.send (C:\Users\%user%\AppData\Local\Programs\feishin\resources\app.asar\dist\main\main.js:14:343069)
    at l.setProperty (C:\Users\%user%\AppData\Local\Programs\feishin\resources\app.asar\dist\main\main.js:14:342089) {
  code: 'ERR_SOCKET_CLOSED'
}
```
after some time (this repeats every few seconds):
```powershell
MPV failed to load next song {
  errcode: 10,
  verbose: 'IPC connection error',
  method: 'connect ETIMEDOUT \\\\.\\pipe\\mpvserver',
  arguments: 'load()',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (C:\\Users\\%user%\\AppData\\Local\\Programs\\feishin\\resources\\app.asar\\dist\\main\\main.js:14:340955)\n' +
    '    at Socket.<anonymous> (C:\\Users\\%user%\\AppData\\Local\\Programs\\feishin\\resources\\app.asar\\dist\\main\\main.js:14:363319)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:157:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:122:3)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:83:21)'
}
```
## Steps to Reproduce

1. Download a script for mpv (that worked for me: https://github.com/NaiveInvestigator/mpv-config or https://github.com/x0wllaar/MPV-SMTC)

2. Open / Restart Feishin

3. Start any music with mpv

4. it will be stuck

## Possible Solution (Not obligatory)
use as a parameter
```powershell
--load-scripts=no
```

## Context

I cant use get it to work with my Windows Media Player and to my rainmeter skin without these scripts

## Your Environment
- Feishin 0.3.0
- Windows 11 22H2
- jellyfin 10.8.10 - Linux

**Comment by jeffvli** [comment]
Fixed in #247
