### ISSUE TITLE
 Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

### ISSUE THREAD

**Issue by yourwifelikesmemore** [jeffvli/feishin#281]
## Expected Behavior

The application opens.

## Current Behavior

A JavaScript error occurred in the main process
Uncaught Exception:
Error: unknown address type:disabled
    at createStream (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/connection.js:64:17)
    at createConnection (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/connection.js:81:33)
    at createClient (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/index.js:10:20)
    at Object.sessionBus (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/index.js:41:10)
    at Player.init (/usr/share/feishin/resources/app.asar/node_modules/mpris-service/src/index.js:183:20)
    at new Player (/usr/share/feishin/resources/app.asar/node_modules/mpris-service/src/index.js:175:8)
    at Player (/usr/share/feishin/resources/app.asar/node_modules/mpris-service/src/index.js:168:12)
    at Object.91312 (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:510323)
    at n (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:803887)
    at Object.44511 (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:501892)
[157550:1006/114600.037522:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[157550:1006/114600.037763:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")

## Steps to Reproduce

1. Start the app in the command line.

## Context

I'm attempting to open the app and I get this error message instead.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.4.0-1
-   Operating System and version (e.g. Windows 10) : Archlinux
-   Server and version (e.g. Navidrome v0.48.0) : 0.49.3 (8b93962f)

**Comment by iiPythonx** [comment]
Running Feishin 0.4 from the command line on Arch doesn't give me this error.
From the looks of it, its MPRIS related so possibly a desktop issue?

**Comment by kgarner7** [comment]
Also on Arch here. Is `DBUS_SESSION_BUS_ADDRESS` set in your environment? For example, in my case it is `unix:path=/run/user/$USER_ID/bus`.

**Comment by yourwifelikesmemore** [comment]
The issue is resolved for me. First I did a fresh install. The app worked until I installed packages from my pkglist.txt. Then I had the same issue. So I did another fresh install, this time without installing packages from my pkglist.txt. The app still works. So there is an app somewhere in my pkglist that causes the issue. Not sure what app it is.

**Comment by mariorossi77** [comment]
export $(dbus-launch)
