### ISSUE TITLE
Unable to play anything. "Unable to load file or stream"

### ISSUE THREAD

**Issue by K0SS4** [jeffvli/feishin#348]
## Expected Behavior
Album/song plays normally

## Current Behavior
When I play an album it skips the first(or first two) songs and hangs on the next. When I search for a specific song and play it then it just hangs and doesn't play anything.

## Steps to Reproduce
Stack trace when I click play on a album:

```
MPV Event: status volume 50 []
MPV Event: status filename stream.view?id=e1c08db65158302a6098c4c9c1077723&v=1.13.0&c=feishin_&u=redacted&s=redacted&t=redacted []
MPV Event: status path https:///mydomain.redacted/rest/stream.view?id=e1c08db65158302a6098c4c9c1077723&v=1.13.0&c=feishin_&u=redacted&s=redacted&t=redacted []
MPV Event: status media-title stream.view?id=e1c08db65158302a6098c4c9c1077723&v=1.13.0&c=feishin_&u=redacted&s=redacted&t=redacted []
MPV Event: status playlist-pos 0 []
MPV Event: status playlist-count 1 []
MPV Event: status pause false []
MPV Event: stopped
MPV failed to load song {
  errcode: 0,
  verbose: 'Unable to load file or stream',
  method: 'emit()',
  arguments: [
    'https:///mydomain.redacted/rest/stream.view?id=e1c08db65158302a6098c4c9c1077723&v=1.13.0&c=feishin_&u=redacted&s=redacted&t=redacted'
  ],
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:363841\n' +
    '    at Array.forEach (<anonymous>)\n' +
    '    at Socket.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:363656)\n' +
    '    at Socket.emit (node:events:513:28)\n' +
    '    at addChunk (node:internal/streams/readable:324:12)\n' +
    '    at readableAddChunk (node:internal/streams/readable:297:9)\n' +
    '    at Socket.Readable.push (node:internal/streams/readable:234:10)\n' +
    '    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)'
}
MPV Event: status filename undefined []
MPV Event: status path undefined []
MPV Event: status media-title undefined []
MPV Event: status playlist-pos -1 []
MPV Event: status pause true []
(node:116978) UnhandledPromiseRejectionWarning: #<Object>
(node:116978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
MPV Event: status playlist-count 0 []
MPV Event: status playlist-count 1 []
```
**Notice that I redacted some(I think) personal stuff**
It's probably worth mentioning that the link `https:///mydomain.redacted/rest/stream.view?id=e1c08db65158302a6098c4c9c1077723&v=1.13.0&c=feishin_&u=redacted&s=redacted&t=redacted`
works fine in my browser(plays the stream normally)

Stack trace when I launch feishin(idk if relevant):
```
[126382:1101/175404.675488:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[126382:1101/175404.675587:ERROR:select_file_dialog_linux_portal.cc(274)] Failed to read portal version property
Initializing MPV with data:  {
  extraParameters: [],
  properties: {
    speed: 1,
    'audio-exclusive': 'no',
    'gapless-audio': 'weak',
    replaygain: 'no',
    'replaygain-clip': true,
    'replaygain-preamp': 0
  }
}
Setting mpv params:  [
  '--idle=yes',
  '--no-config',
  '--load-scripts=no',
  '--prefetch-playlist=yes'
]
Error in main process Error: Socket is closed
    at new NodeError (node:internal/errors:399:5)
    at Socket._writeGeneric (node:net:920:8)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.Writable.write (node:internal/streams/writable:337:10)
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:343343
    at new Promise (<anonymous>)
    at l.send (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:343069)
    at l.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:342089) {
  code: 'ERR_SOCKET_CLOSED'
}
MPV failed to set volume {
  errcode: 8,
  verbose: 'MPV is not running',
  method: 'volume()',
  stackTrace: 'Error: \n' +
    '    at e.exports.errorMessage (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:340955)\n' +
    '    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:343165\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at l.send (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:343069)\n' +
    '    at l.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:342089)\n' +
    '    at y.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:344520)\n' +
    '    at y.volume (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:346750)\n' +
    '    at IpcMainImpl.<anonymous> (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:501125)\n' +
    '    at IpcMainImpl.emit (node:events:513:28)\n' +
    '    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88632)'
}
(node:126382) UnhandledPromiseRejectionWarning: #<Object>
(Use `feishin --trace-warnings ...` to show where the warning was created)
(node:126382) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Setting MPV properties:  {
  speed: 1,
  'audio-exclusive': 'no',
  'gapless-audio': 'weak',
  replaygain: 'no',
  'replaygain-clip': true,
  'replaygain-preamp': 0
}
```
EDIT: Recording of this happening: https://streamable.com/cxa77i (cannot put videos directly).

## Possible Solution (Not obligatory)
I think it's either some missing dependency or a bug specific to my navidrome version(4.9.3) because it's a major bug and I haven't seen any bug reports yet.

EDIT: I checked README section about mpv switching states between play and pause so I guess it's also a suspect.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.0 feishin-bin from AUR(I tried feishin-appimage and the .tar.xz from releases but same result). EDIT: Tried 0.4.1 but same result.
-   Operating System and version (e.g. Windows 10) : Arch Linux (using wayland but the same happens on xorg for me)
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.49.3
-   Mpv version: 0.36.0 (tried setting /usr/bin/mpv and /bin/mpv but neither works)

**Comment by K0SS4** [comment]
After removing and adding the server again it works fine. Idk what happend since previous configuration was fine(the stream urls from logs worked fine in browser and I could browse my library in feishin). Closing the issue I guess.
