### ISSUE TITLE
Feishin connects to navidrome but nothing loads

### ISSUE THREAD

**Issue by jpecora716** [jeffvli/feishin#407]
## Expected Behavior

The Dashboard should load after successfully connecting to Navidrome

## Current Behavior

Nothing loads. In the past this would've loaded right away. I can connect using Sonixd without any problems.
![image](https://github.com/jeffvli/feishin/assets/6646235/490722a7-c051-4c3b-b9a4-9f0a2ba7c0bd)

## Steps to Reproduce

1. Launch feishin
2. Select mpv path
3. Connect to navidrome

```
❯ feishin
21:13:58.943 › APPIMAGE env is not defined, current application is not an AppImage
[17445:1212/211400.166217:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[17445:1212/211400.180144:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Initializing MPV with data:  {
  extraParameters: [],
  properties: {
    speed: 1,
    'audio-exclusive': 'no',
    'gapless-audio': 'weak',
    replaygain: 'no',
    'replaygain-clip': true,
    'replaygain-preamp': 0
  }
}
Setting mpv params:  [
  '--idle=yes',
  '--no-config',
  '--load-scripts=no',
  '--prefetch-playlist=yes'
]
Error in main process Error: Socket is closed
    at new NodeError (node:internal/errors:405:5)
    at Socket._writeGeneric (node:net:921:8)
    at Socket._write (node:net:943:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Socket.write (node:internal/streams/writable:337:10)
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:343343
    at new Promise (<anonymous>)
    at l.send (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:343069)
    at l.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:342089) {
  code: 'ERR_SOCKET_CLOSED'
}
Setting MPV properties:  {
  speed: 1,
  'audio-exclusive': 'no',
  'gapless-audio': 'weak',
  replaygain: 'no',
  'replaygain-clip': true,
  'replaygain-preamp': 0
}
MPV Event: status pause true []
MPV Event: status duration undefined []
MPV Event: status volume 50 []
MPV Event: status filename undefined []
MPV Event: status path undefined []
MPV Event: status media-title undefined []
MPV Event: status playlist-pos -1 []
MPV Event: status playlist-count 0 []
MPV Event: status loop false []
```

## Context

Unable to use feishin - Sonixd still works

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.2
-   Operating System and version (e.g. Windows 10) : Manjaro
-   Server and version (e.g. Navidrome v0.48.0) : Navidrome 0.50.1-SNAPSHOT (54597bd5)

**Comment by jeffvli** [comment]
Thanks!

**Comment by jeffvli** [comment]
Try downloading and installing the [linux binaries](https://github.com/jeffvli/feishin/actions/runs/7190115112) from @kgarner7's PR and let me know if that resolves it.

**Comment by jpecora716** [comment]
Yes, that resolves my issue. Thank you
