### ISSUE TITLE
Cannot find latest-linux.yml in the latest release artifacts & White Screen with Linux AppImage

### ISSUE THREAD

**Issue by ScaldedWilder** [jeffvli/feishin#436]
## Expected Behavior

Launch Feishin AppImage on Linux. It should successfully launch the application regardless if "https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml is found.

Believe Quick fix is to upload Latest-Linux.yml to the latest release. Long term, it should hopefully not create an error & stacktrace when not found - just a warning.

## Current Behavior

I launch the AppImage on Linux

I get the an error that : "Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml): HttpError: 404" (Full error below)

Afterwards, the application doesn't open. From the toolbar if I ask to show main dialog, it shows me a blank screen.
* Disclaimer on this last part: I am on a fresh install of TumbleWeed. It's possible the latest-linux.yml is not causing this - just an earlier failure. Once latest-linux.yml is added, I can confirm if my blank screen issues persist

![image](https://github.com/jeffvli/feishin/assets/153934407/d41c6cb7-218e-42b1-854c-ad5bfc3e9ad0)

## Steps to Reproduce

Download a recent x86_64 linux AppImage
Set as executable
Launch via terminal (optionally with --trace-warnings)

```
18:46:28.227 › Checking for update
18:46:29.207 › Error: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Sun, 07 Jan 2024 23:45:49 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "E4DC:5EFE:17AAB4F:203DAC7:659B37D5",
  "x-xss-protection": "0"
}
    at d (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:47269)
    at s.handleResponse (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:49124)
    at ClientRequest.<anonymous> (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:48579)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49818)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at Object.t.newError (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:57439)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:145801)
    at d.getUpdateInfoAndProvider (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:102447)
    at doCheckForUpdates (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:102733)
(node:10099) UnhandledPromiseRejectionWarning: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Sun, 07 Jan 2024 23:45:49 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "E4DC:5EFE:17AAB4F:203DAC7:659B37D5",
  "x-xss-protection": "0"
}
    at d (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:47269)
    at s.handleResponse (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:49124)
    at ClientRequest.<anonymous> (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:48579)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49818)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at Object.t.newError (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:57439)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:145801)
    at d.getUpdateInfoAndProvider (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:102447)
    at doCheckForUpdates (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:102733)
    at emitUnhandledRejectionWarning (node:internal/process/promises:200:15)
    at processPromiseRejections (node:internal/process/promises:296:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:10099) Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml): HttpError: 404 
"method: GET url: https://github.com/jeffvli/feishin/releases/download/v0.5.3/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": "no-cache",
  "content-encoding": "gzip",
  "content-length": "29",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-type": "text/plain; charset=utf-8",
  "date": "Sun, 07 Jan 2024 23:45:49 GMT",
  "referrer-policy": "no-referrer-when-downgrade",
  "server": "GitHub.com",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "x-content-type-options": "nosniff",
  "x-frame-options": "deny",
  "x-github-request-id": "E4DC:5EFE:17AAB4F:203DAC7:659B37D5",
  "x-xss-protection": "0"
}
    at d (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:47269)
    at s.handleResponse (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:49124)
    at ClientRequest.<anonymous> (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:48579)
    at ClientRequest.emit (node:events:514:28)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49818)
    at SimpleURLLoaderWrapper.emit (node:events:514:28)
    at Object.t.newError (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:8:57439)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:145801)
    at d.getUpdateInfoAndProvider (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:102447)
    at doCheckForUpdates (/tmp/.mount_FeishiSqovgm/resources/app.asar/dist/main/main.js:14:102733)

```
## Possible Solution (Not obligatory)

The first step would be to add the latest-linux.yml to the latest release, which will let me diagnose if the blank screen failure is fixed - or a separate issue.

## Context
Application unusable in current state on this system. the latest works on my Windows 10 system.

## Your Environment

-   Application version (e.g. v0.1.0) : 0.5.3 and 0.5.2 both tested as failing this way
-   Operating System and version (e.g. Windows 10) : TumbleWeed 20240106 (kernel: 6.6.9-1-default (64-bit))
-   Server and version (e.g. Navidrome v0.48.0) : Unrelated. No Navidrome connection was made. 
-   Node version (if developing locally) : NA

**Comment by ScaldedWilder** [comment]
Closing this because after several reboots and installing other codecs, mounts, updates on the system - Feishin seems to be working again.
