### ISSUE TITLE
can't start the app after upgraded to v0.6.0 

### ISSUE THREAD

**Issue by tixwho** [jeffvli/feishin#538]
## Current Behavior

stuck at starting the program after upgraded to version 0.6.0, connected to selfhosted navidrome

https://github.com/jeffvli/feishin/assets/44349672/13133f1e-e8a3-4f61-83e3-f44c0b6a9240

## Steps to Reproduce

upgraded to v0.6.0 using AUR.

in feishin v0.5.3 I did notice that I have to re-login almost every day, but I didn't put too much thoughts on it.

here's the console output

```
$ feishin                                                                                                              
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:12.272 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:12.635 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:12.961 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:13.287 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:13.614 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:13.940 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:14.265 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:14.591 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:14.917 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:15.242 › [AUDIO PLAYER] Setting properties: {"speed":1}
Error occurred in handler for 'password-get': Error: Error while decrypting the ciphertext provided to safeStorage.decryptString.
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:523548
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:88656)
    at WebContents.emit (node:events:514:28)
17:37:15.568 › [AUDIO PLAYER] Setting properties: {"speed":1}
```
and here's the mpv version, if useful:
```
$ mpv --version
mpv v0.37.0 Copyright © 2000-2023 mpv/MPlayer/mplayer2 projects
 built on Jan 19 2024 09:09:45
libplacebo version: v6.338.2
FFmpeg version: n6.1.1
FFmpeg library versions:
   libavutil       58.29.100
   libavcodec      60.31.102
   libavformat     60.16.100
   libswscale      7.5.100
   libavfilter     9.12.100
   libswresample   4.12.100
```

## Your Environment

Application version (e.g. v0.1.0) : v0.6.0-1, AUR installed
Operating System and version (e.g. Windows 10) : KDE Plasma 5.27.10; Manjaro 6.6.19-1; Qt 5.15.12
Server and version (e.g. Navidrome v0.48.0) : Navidrome v.051.1

**Comment by iiPythonx** [comment]
Known issue in the discord server, fixing it should be as simple as:
- Opening inspect via CTRL+SHIFT+I.
- Navigating to the Application tab at the top of the inspect panel.
- Selecting `store_authentication` and hitting the delete key:

![image](https://github.com/jeffvli/feishin/assets/35084023/51353b7b-6093-427b-a746-9cbcf322235d)
- Relaunching Feishin.

**Comment by tixwho** [comment]
Thanks for the prompt response and easy-to-follow instruction, problem resolved! I'll close the issue now
