### ISSUE TITLE
[AppImage] Error: unknown address type:disabled

### ISSUE THREAD

**Issue by dannyloxavier** [jeffvli/feishin#57]
## Prerequisites

- [x] Using AppImage :eyes: 
- [ ] Using npm
- [ ] Using an up-to-date [`main` branch](https://github.com/electron-react-boilerplate/electron-react-boilerplate/tree/main)
- [ ] Using latest version of devtools. [Check the docs for how to update](https://electron-react-boilerplate.js.org/docs/dev-tools/)
- [ ] Tried solutions mentioned in [#400](https://github.com/electron-react-boilerplate/electron-react-boilerplate/issues/400)
- [ ] For issue in production release, add devtools output of `DEBUG_PROD=true npm run build && npm start`

## Expected Behavior

Lauch the linux x86_64 AppImage and use feishin. :smile: 

## Current Behavior

The AppImage version isn't launching feishin.
If I try to run via cli, I get an `Uncaught Exception` message.

## Steps to Reproduce

1. Download the latest version of the Feishin AppImage for linux x86_64.

2. Give exec permission to the AppImage with: `chmod +x feishin.AppImage`

3. Try to open the program with: `./feishin.AppImage`

4. The program returns this message:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: unknown address type:disabled
    at createStream (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/dbus-next/lib/connection.js:64:17)
    at createConnection (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/dbus-next/lib/connection.js:81:33)
    at createClient (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/dbus-next/index.js:10:20)
    at Object.sessionBus (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/dbus-next/index.js:41:10)
    at Player.init (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/mpris-service/src/index.js:183:20)
    at new Player (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/mpris-service/src/index.js:175:8)
    at Player (/tmp/.mount_feishiSt03qi/resources/app.asar/node_modules/mpris-service/src/index.js:168:12)
    at Object.91312 (/tmp/.mount_feishiSt03qi/resources/app.asar/dist/main/main.js:14:459811)
    at r (/tmp/.mount_feishiSt03qi/resources/app.asar/dist/main/main.js:14:541282)
    at Object.95909 (/tmp/.mount_feishiSt03qi/resources/app.asar/dist/main/main.js:14:459576)
[2478:0317/210227.892328:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2478:0317/210227.892407:ERROR:bus.cc(399)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
```

## Possible Solution (Not obligatory)

Maybe something here can help: https://github.com/electron/electron/issues/31981

## Context

Just knew about the project. I'm trying to use the program. It looks awesome! :+1: 

## Your Environment

- Node version : v16.19.0
- electron-react-boilerplate version or branch : -
- Operating System and version : Void Linux x86_64 glibc
- Link to your project : -
- I'm using qtile with Xorg.
- I'm using other electron apps and electron AppImages without issues.

**Comment by ttylta** [comment]
Same thing is happening with me for the latest non-AppImage Linux release.

Using Artix 6.2.6.

**Comment by jeffvli** [comment]
Thanks for reporting.

Most likely due to building the linux app using the macOS runner (happened with Sonixd as well https://github.com/jeffvli/sonixd/issues/255).

I'll switch to a linux runner for builds in the next release.

**Comment by jeffvli** [comment]
Added in [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6).

**Comment by dannyloxavier** [comment]
I tested today and I have the same error message and problem. =(

**Comment by jeffvli** [comment]
@dannyloxavier Strange.. can you try using the workaround that was posted? https://github.com/jeffvli/sonixd/issues/153#issuecomment-999299110

You can also try cloning the repo and building the app locally to see if it will work.

```
git clone https://github.com/jeffvli/feishin.git
npm install
npm run package

AppImage should be built under './release'
```

**Comment by dannyloxavier** [comment]
Doing the 'git, npm install, npm run package' doesn't solve the problem.
Doing the workaround solved! =)

When I did the `npm install`, I got 16 vulnerabities (3 moderate, 13 high). Should I be worried?

**Comment by hatkidchan** [comment]
Same happens to me on Arch now w/ Feishin 0.7.1 (both `feishin-appimage` and `feishin-bin` don't start up)
Running appimage from source also results in the same error


```
Error: unknown address type:disabled
    at createStream (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/dbus-next/lib/connection.js:64:17)
    at createConnection (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/dbus-next/lib/connection.js:81:33)
    at createClient (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/dbus-next/index.js:10:20)
    at Object.sessionBus (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/dbus-next/index.js:41:10)
    at Player.init (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/mpris-service/src/index.js:183:20)
    at new Player (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/mpris-service/src/index.js:175:8)
    at Player (/tmp/.mount_FeishizS422G/resources/app.asar/node_modules/mpris-service/src/index.js:168:12)
    at Object.91312 (/tmp/.mount_FeishizS422G/resources/app.asar/dist/main/main.js:14:525033)
    at n (/tmp/.mount_FeishizS422G/resources/app.asar/dist/main/main.js:14:821378)
    at Object.44511 (/tmp/.mount_FeishizS422G/resources/app.asar/dist/main/main.js:14:516329)
```

**Comment by hatkidchan** [comment]
Curiously, workaround in https://github.com/jeffvli/sonixd/issues/153#issuecomment-999299110 still works.

**Comment by hatkidchan** [comment]
Actually, problem was on my side, after a long uptime my dbus broke and I couldn't even reboot normally, but after reboot it works fine. Ignore previous messages, except second one which could help to some.
