### ISSUE TITLE
Crossfade is totally broken

### ISSUE THREAD

**Issue by pyxfluff** [jeffvli/feishin#665]
### Expected Behavior

If you enable crossfade on the Web player, it should work.

### Current Behavior

It does not do anything. Playback continues as expected, but you get an out of range error.

### Steps to Reproduce

1. Enable Crossfade
2. Listen to some music
3. You will see this exception in the console:
```js
renderer.js:10 Uncaught DOMException: Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (6.26052) is outside the range [0, 1].
    at e.crossfadeHandler (file:///C:/Users/darkp/AppData/Local/Programs/feishin/resources/app.asar/dist/renderer/renderer.js:10:6348)
    at Object.onProgress (file:///C:/Users/darkp/AppData/Local/Programs/feishin/resources/app.asar/dist/renderer/renderer.js:10:2752)
    at file:///C:/Users/darkp/AppData/Local/Programs/feishin/resources/app.asar/dist/renderer/renderer.js:2:17194102
```

### Application version

0.7.1

### Operating System and version

Windows 11 Desktop

### Server and Version

Navidrome 0.51.0

**Comment by kgarner7** [comment]
Resolved by https://github.com/jeffvli/feishin/commit/616fd457345ade55df1457874c3a309461cb4f14

**Comment by urielc918** [comment]
I'm having the same issue with 0.12.1 on Windows 11 23H2
```
Uncaught DOMException: Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (21.892) is outside the range [0, 1].
    at e.crossfadeHandler (file:///C:/Users/user/AppData/Local/Programs/feishin/resources/app.asar/dist/renderer/renderer.js:10:6963)
    at Object.onProgress (file:///C:/Users/user/AppData/Local/Programs/feishin/resources/app.asar/dist/renderer/renderer.js:10:3336)
    at file:///C:/Users/user/AppData/Local/Programs/feishin/resources/app.asar/dist/renderer/renderer.js:2:17178414
```

**Comment by pyxfluff** [comment]
Yeah I'm seeing this still on Linux too

```
Uncaught DOMException: Failed to set the 'volume' property on 'HTMLMediaElement': The volume provided (4.56581) is outside the range [0, 1].
    at e.crossfadeHandler (file:///usr/share/feishin/resources/app.asar/dist/renderer/renderer.js:10:6909)
    at Object.onProgress (file:///usr/share/feishin/resources/app.asar/dist/renderer/renderer.js:10:3522)
    at file:///usr/share/feishin/resources/app.asar/dist/renderer/renderer.js:2:17179121
```
