### ISSUE TITLE
Can't find mpv in Path on Linux

### ISSUE THREAD

**Issue by exu-g** [jeffvli/feishin#99]
## Expected Behavior

MPV binaries in the environment PATH should be found correctly.

## Current Behavior

On first launch, feishin asks the user to select the path to mpv.  
![image](https://github.com/jeffvli/feishin/assets/61015582/ec79cefe-0705-4687-b5c8-8918cae87fcd)

I'm not sure whether you can read anything from the logs, but here they are anyways:  
```
marc@vladilena ~> feishin

(feishin:1146307): Gtk-WARNING **: 08:23:17.907: Theme parsing error: gtk.css:5822:26: '-shadow' is not a valid color name

(feishin:1146307): Gtk-WARNING **: 08:23:17.907: Theme parsing error: gtk.css:5825:14: not a number

(feishin:1146307): Gtk-WARNING **: 08:23:17.907: Theme parsing error: gtk.css:5826:13: not a number

(feishin:1146307): Gtk-WARNING **: 08:23:17.907: Theme parsing error: gtk.css:5827:11: Expected a length
08:23:18.005 › APPIMAGE env is not defined, current application is not an AppImage
(node:1146307) UnhandledPromiseRejectionWarning: #<Object>
(Use `feishin --trace-warnings ...` to show where the warning was created)
(node:1146307) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Error in main process Error: Socket is closed
    at new NodeError (node:internal/errors:387:5)
    at Socket._writeGeneric (node:net:864:8)
    at Socket._write (node:net:886:8)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at /usr/share/feishin/resources/app.asar/dist/main/main.js:14:311807
    at new Promise (<anonymous>)
    at l.send (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:311556)
    at l.setProperty (/usr/share/feishin/resources/app.asar/dist/main/main.js:14:310576) {
  code: 'ERR_SOCKET_CLOSED'
}
Error: Data: none was not of type boolean
    at checkBoolean (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshallers.js:249:73)
    at Object.MakeSimpleMarshaller.marshaller.check (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshallers.js:112:9)
    at Object.MakeSimpleMarshaller.marshaller.marshall [as marshall] (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshallers.js:115:14)
    at writeSimple (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:104:20)
    at write (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:80:14)
    at write (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:77:7)
    at writeStruct (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:34:5)
    at write (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:44:7)
    at write (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:59:47)
    at writeStruct (/usr/share/feishin/resources/app.asar/node_modules/dbus-next/lib/marshall.js:34:5)
(node:1146307) UnhandledPromiseRejectionWarning: #<Object>
(node:1146307) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

## Steps to Reproduce

1. Extract Linux tar.xz release

2. Execute feishin

## Your Environment

My PATH variable contains the `/usr/bin` directory among others.  
MPV is located at `/usr/bin/mpv`  

- OS: Arch Linux  
- Feishin version: [0.0.1-alpha6](https://github.com/jeffvli/feishin/releases/tag/v0.0.1-alpha6)
- PATH variable: `/usr/local/bin /usr/bin /bin /usr/local/sbin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl`
- Node version: 16.20.0

**Comment by jeffvli** [comment]
This is intended behavior. I'm currently forcing all users to manually input the path to their mpv executable since the MPV controller module that I'm using doesn't support controlling from the PATH in Windows. I may update this behavior in the future because it definitely does hurt UX on the out of the box experience.

If you click the input box, you should be able to navigate to and select the mpv executable.

**Comment by exu-g** [comment]
Ok, thank you for the quick response and the explaination.  
Navigating to the executable works, as you mentioned.  
Feel free to close this issue and have a nice day!
